### ISSUE TITLE
issues starting up from current documentation

### ISSUE THREAD

**Issue by naterock101** [thieryw/gitlanding#10]
thanks for starting the gitlanding framework. Looks very cool for getting projects up quickly. I followed the instructions on the docs page and youtube and i run into some errors viewing the base react app page (with the react logo).

I noticed that the deploy.yaml script that is created as of now using this command: wget gitlanding.dev/deploy.yaml -O .github/workflows/deploy.yaml

is slightly different then the one you have on https://github.com/thieryw/gitlanding/blob/landingpage/.github/workflows/deploy.yml

i have tried switching to that one but run into the same issue where all i get is a blank react page and nothing seems to render/load with a few 404s

any thoughts on this or updates that we should be aware of?

**Comment by garronej** [comment]
Hi @naterock101,  
Thank you for your feedback and sorry for the issue you are facing.  
I will have a look right now.

**Comment by garronej** [comment]
Ok I see the problem, my bad!

**Comment by garronej** [comment]
Hold on I am sorry, almost done

**Comment by garronej** [comment]
It should be fixed now, you'll just have to run this command again
```bash
wget gitlanding.dev/deploy.yaml -O .github/workflows/deploy.yaml
```  
Thank you very much for reporting!
