### ISSUE TITLE
GitBook customization

### ISSUE THREAD

**Issue by garronej** [thieryw/gitlanding#7]
![image](https://user-images.githubusercontent.com/6702424/135921943-4af6b3be-233f-4e09-b3af-1f1a9054f6e3.png)

- Orange is the focus color it can **NEVER** be used as a background color or anything that isn't interactive. The background color in the theme is #2C323F in dark mode or #F1F0EB in light mode. 
- There is an option for using a full logo in the header but you didn't use it.
- We comited to sans-serif in the landingpage so we should use `open sans` for homogeneity sake. 
- You didn't add the link in the header.

**Comment by thieryw** [comment]
Thank you verry much, I wholeheartedly endorse those changes.

**Comment by garronej** [comment]
![image](https://user-images.githubusercontent.com/6702424/135992689-f56e2e01-ad7d-41e3-86fe-87e936ff10ed.png)
It's better like that considering we can't have a darl mode
